name: Release Version
run-name: Release Version
description: Will release a new version of the backend.

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            frontend

      - name: Install dependencies
        run: |
          # Setup minhtml, a tool to minify HTML files
          wget https://github.com/wilsonzlin/minify-html/releases/download/v0.18.1/minhtml-0.18.1-x86_64-unknown-linux-gnu -O minhtml
          chmod +x minhtml
          mv minhtml /usr/local/bin/minhtml

          # Setup NodeJS
          NODE_VERSION=$(cat frontend/.nvmrc | tr -d 'vV')
          echo "Node version: $NODE_VERSION"
          wget https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz -O node.tar.gz
          tar -xzf node.tar.gz
          mv node-v${NODE_VERSION}-linux-x64 /opt/nodejs
          PATH="/opt/nodejs/bin:$PATH"

          # Install project dependencies
          cd frontend
          npm install

      - name: Bundle frontend
        run: |
          cd frontend
          npm run build
          npm run bundle

      - name: Archive frontend
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend/dist/index.min.html

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            backend

      - name: Install dependencies
        run: |
          # Installing go

          GO_VERSION=$(grep go backend/go.mod | head -1 | cut -d' ' -f2)
          echo "Go version: $GO_VERSION"

          # Install project dependencies
          cd backend
          go mod download

      - name: Build backend
        run: |
          cd backend
          make build

      - name: Archive backend
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend/bin/webserver

  deploy:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Download frontend
        uses: actions/download-artifact@v5
        with:
          name: frontend
          path: frontend

      - name: Download backend
        uses: actions/download-artifact@v5
        with:
          name: backend
          path: backend

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known hosts
        env:
          SSH_HOST: ${{ secrets.VPS_IP }}
          SSH_PORT: ${{ secrets.VPS_SSH_PORT }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $SSH_PORT -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: SSH to VPS
        env:
          SSH_HOST: ${{ secrets.VPS_IP }}
          SSH_USER: root
          SSH_PORT: ${{ secrets.VPS_SSH_PORT }}
        run: |
          set -x
          ls
          ls frontend
          ls backend
          ssh $SSH_USER@$SSH_HOST -p $SSH_PORT "mkdir -p /var/q/html /var/q/backend"
          scp -P $SSH_PORT frontend/index.html $SSH_USER@$SSH_HOST:/var/q/html/
          scp -P $SSH_PORT backend/webserver $SSH_USER@$SSH_HOST:/var/q/backend/
      